language: node_js
sudo: false
node_js: stable
addons:
  sauce_connect: true
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
env:
  global:
  - secure: pJThsDLKpP+BhDlbCaQY5at0D7HoMhfn4r8+Gnav/OReZB8Dsz7Qefz9QzygXkFh+7S5YRUtaOMS9OfNeFUoxUK+xkGye4CQDN0d1zh+5+z1dI0N6pU38nK28MoWiZR5TPywOR8DR+Ec+8dlaBvfvpqv8hytVoNuDa3WYQHkQs2ihLBoVuvBN3OIwI13zM73yDw8up5jjhWHnW/uwzKi8FF7V7IBJNrDX7CLZ5rCQbPICuFDPbcNJDnfupkjQwX2irlST2CCHRzKG9z/XNOV5bre2c3JYcZ2r9csyQewcwGwN8G2KnlFvHLM/QvlVdf4DJrLkEj2HaXUbWOBegLkRmZfjSwMUlxAnBNvXecuj1szr9FftINvuvMmWsoGNCkL/UfmF9Bb1zFrYCo7puF+JpGSMNWrPCc8CwxRZ6Kr5RBUE8wE9SJ8Bw6Mjn0ghUhezyE8wAolk1rGVS3/hvk86v+AFQNKut3cwc2b4RtvVLU7zuY/jAHlWQyTCElbuJyInBKt0NnmG+BPtLHjO0J6Z/OlYUxp3B5UGR8ey5OeB4wt6XWX812fpqZnYO38xO+Jbp8mqo4XsBQkm8RptXXt2IggUrI+6DKZ2kiGoCR5R1FIwIb127dz2V6L2MBW8VLQhpvEMVFt0HLY6nlIU3xhgtik/IDxuFdi27ckqcrI2M4=
  - secure: OAcCODrXJ9iBRginZTxiPdG8vw7e1mwrwwQQZXK+UyAmDak33r6w1PNvwfQpuWExYPGy0o6aiBelPCVYmjuKCiXhCSlDe4bxZdWOaQto/w2zcpI3xugUHS62hNv5PrwU6Xl3zqgNTSBYI00TJ4krInDIub4A///zOdMDLqOs+OyatIPP2EAyY4Sl3UIdtFXuRubL1Y8DHhHjJ9Sd1LQPEcWwNJwm66MUYybHfW4p0KE0PueCLXXKPvaoEdAjFNzAncmbiDcECPwCESFLBiCmhWjw8p+MIC9VZUrtmDACou9V9nm8J5Ko3zea+ZRLMIlQsTS6vGX1SGBSezdGtuRo/BXIC3XCMDZwVFJ0A51xkm4YvVzgOtucXeg3/qxPBXUjWMoNi3h5flgorCZB6+lkHdH/SPi5YhXydTYpTm8nIF+iJ/+pktWcZT/ZBBFkd95bdtOJJ1bsvv9HiPT5xeMmKK3F7h2tmf6gDzQDAzpNrvu/SS9wQ9SJ1G2r6l925uGK+3nPoar1AT52DPmNHr/2TTnaE6rHZTW8Zv5H5JudoszR9MBc3AONKG6WLp3DOsm+Zt64eW63LZwJfm72z2zkk48V7llGHD0vtWz/m3yrBGWrzcWFwN2RIv+jfm6vix1zDdUVyhJttWfphhVhrjcO7wtLVNiopRbJxjrtKx0c2DE=
